apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-app-secret
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: secret-server-store
    kind: SecretStore
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "52622"  # folder/secret name in Delinea
